### ISSUE TITLE
add support of variable type set of int 

### ISSUE THREAD

**Issue by sthiele** [sthiele/fzn2lp#1]
If the converter stumbles over the `Domain` variants `Domain::SetInt(v)` or `Domain::SetIntNonEmpty(v)` it panics.

**Comment by MaxOstrowski** [comment]
These are Variables of the type `set`, right ? I think this can be translated away using the flatzinc toolchain. If not, I think that we are ok not supporting sets (of we would need to think of in implementation) as not all CP Solvers support set variables.

**Comment by MaxOstrowski** [comment]
We may not need this for variables, but sometimes sets of integers are given as parameters to constraints.
Like
`constraint set_in_reif(X_INTRODUCED_4436_,0..64,X_INTRODUCED_684754_):: defines_var(X_INTRODUCED_684754_);`
or
`constraint set_in_reif(X_INTRODUCED_4155_,{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,24,25,28,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52},X_INTRODUCED_676717_):: defines_var(X_INTRODUCED_676717_);`

It would be crucial to have these notations for flatzingo.
It could come with
```
in(c1,1,set).
in(c1,1,set,1).
in(c1,1,set,3).
in(c1,1,set,5).
in(c1,1,set,7).
```
for
`{1,3,5,7}`
and
```
in(c1,1,set).
in(c1,1,set,0,64).
```
for
`1..64`

**Comment by MaxOstrowski** [comment]
Started learning Rust:
You could probably just expand the vector in line 
SetLiteral::SetInts(v) => panic!("TODO: set_of_ints(v)"),
into a strict of the form` "set_int_elem(1;3;6;8;234)"` and let gringo take care of the rest ?
Not good enough at Rust to propose a PR yet :smirk:

**Comment by sthiele** [comment]
> `constraint set_in_reif(X_INTRODUCED_4436_,0..64,X_INTRODUCED_684754_):: defines_var(X_INTRODUCED_684754_);`

For this variant fzn2lp already produces this output: 

```
constraint(c1,"set_in_reif").
in_constraint(c1,0,"X_INTRODUCED_4436_").
in_constraint(c1,1,set_int_range(0,64)).
in_constraint(c1,2,"X_INTRODUCED_684754_").
```

For the other variant I thought about something like this:

```
constraint(c1,"set_in_reif").
in_constraint(c1,0,"X_INTRODUCED_4436_").
in_constraint(c1,1,set_of_int(s1)).
in_constraint(c1,2,"X_INTRODUCED_684754_").
in_set(s1,0).
in_set(s1,1). ...
```
I think this is more flexible because set literals could appear not only in constraints.

**Comment by MaxOstrowski** [comment]
Unless you want to merge equal sets to one `s1` in your parser, I would recommend to put the number directly into it:
in_constraint(c1,1,set_of_int(1)).
in_constraint(c1,1,set_of_int(2)).
in_constraint(c1,1,set_of_int(4)).

**Comment by sthiele** [comment]
The appearance of the literal `s1` would be unique.

**Comment by sthiele** [comment]
Actually I'm not sure which variant is the better translation for the
flatzinc statement:
```
constraint set_in_reif({1,2,3,4,5},{1,2,3,4,5});
```
Variant 1:
```
constraint(c1, "set_in_reif").
in_constraint(c1, 0, set_of_int(s1)).
in_set(s1,1). 
... 
in_set(s1,5).
in_constraint(c1, 1, set_of_int(s2)).
in_set(s2,1).
... 
in_set(s2,5).
```
Variant 2:
```
constraint(c1, "set_in_reif").
in_constraint(c1, 0, set_of_int(1)).
...
in_constraint(c1, 0, set_of_int(5)).
in_constraint(c1, 1, set_of_int(1)).
...
in_constraint(c1, 1, set_of_int(5)).
```
Variant 1 has this indirection over the `in_set` predicate.
Variant 2 is shorter but for each element of the set we duplicate the constraint id and the position in the constraint. Also set literals can appear as well in variable and parameter declarations I don't know do you deal with them there? 
For array we use variant 2 for array literals in constraints, and for array literals in variable and parameter declarations we have variant 1, because we there we have a variable/parameter name.

**Comment by MaxOstrowski** [comment]
Could you give an example of both array and set in both declarations and literals?
I think we do not need declarations for Flatzingo.
Nevertheless it would be cool if it is uniform in all 4 cases.

**Comment by sthiele** [comment]
An array literal in a parameter declaration:
```
array of int : y = [1,2,3,4];
```
translates to 
```
parameter(array(5,int),"y").
in_array("y",0,1).
in_array("y",1,2).
in_array("y",2,3).
in_array("y",3,4).
```

A set literal in a variable declaration:
```
var set of int : x = {1,2,3,4};
```
could translates to 
```
variable(set_of_int(1),"x").
variable(set_of_int(2),"x").
variable(set_of_int(3),"x").
variable(set_of_int(4),"x").
``` 
or
```
variable(set_of_int(s12),"x").
in_set(s12,1).
in_set(s12,2).
in_set(s12,3).
in_set(s12,4).
```

**Comment by sthiele** [comment]
Also
- Array of set of int as parameter
  ```
  array [1..4] of set of int: y = [{1},{2},{3},{4}];
  ```
- Array of set of int as variable
  ```
  array [1..4] of var set of int: y = [{1},{2},{3},{4}];
  ```

**Comment by sthiele** [comment]
Variant 2 becomes problematic for set of int in set. Where a set literal appears in also in the type position.
This leads to a quadratic translation. See example below.
```
var set of {1,2,3} : o = {1,2,X};
```
translates with variant 2 to
```
variable(set_of_int_in_set(1),"o",set_of_int(1)).
variable(set_of_int_in_set(1),"o",set_of_int(2)).
variable(set_of_int_in_set(1),"o",set_of_int("X")).
variable(set_of_int_in_set(2),"o",set_of_int(1)).
variable(set_of_int_in_set(2),"o",set_of_int(2)).
variable(set_of_int_in_set(2),"o",set_of_int("X")).
variable(set_of_int_in_set(3),"o",set_of_int(1)).
variable(set_of_int_in_set(3),"o",set_of_int(2)).
variable(set_of_int_in_set(3),"o",set_of_int("X")).
```

**Comment by sthiele** [comment]
Solved in master
