### ISSUE TITLE
Array Konstanten

### ISSUE THREAD

**Issue by MaxOstrowski** [sthiele/fzn2lp#11]
[example.zip](https://github.com/sthiele/fzn2lp/files/4780182/example.zip)

Array Konstanten wie 
`array [1..2] of int: X_INTRODUCED_103_ = [1,-1];`
werden nicht mehr richtig abgebildet in constraints:
`constraint int_lin_le(X_INTRODUCED_103_,[X_INTRODUCED_0_,X_INTRODUCED_1_],-88);`
Führt zu
```
constraint(c1,"int_lin_le").                                                                           
in_constraint(c1,0,"X_INTRODUCED_103_").                                                               
in_constraint(c1,1,array_of_bool(0,"X_INTRODUCED_0_")).                                                
in_constraint(c1,1,array_of_bool(1,"X_INTRODUCED_1_")).                                                
in_constraint(c1,2,-88).
```
Früher wurde für param 0 ein in_array erzeugt.
Ausserdem ist der zweite Parameter vom Typ array_of_int (ein array von integer variablen).

**Comment by MaxOstrowski** [comment]
There is probably a similar thing for sets ?

**Comment by sthiele** [comment]
The only problem I see is the `array_of_bool`. It is impossible to know which type the array has without regarding the context. `array_of_bool` is simply the first type that matches. One would need to check the type of the previously defined variables/predicate signatures that are used in the constraint.
I could either add more book keeping to enable such type checks or we just remove the type information from the array expr ?
Instead of `array_of_bool`, `array_of_int`, `array_of_float`, `array_of_set` something like `array_at(Idx,Val)`.

Otherwise it is like I intended it `in_array` is gone.

```
array [1..2] of int: X_103 = [1,-1];
constraint int_lin_le(X_103,[X_0,X_1],-88);
solve satisfy;
```
translates to 
```
parameter("X_103",array(2,int),array_at(0,1)).
parameter("X_103",array(2,int),array_at(1,-1)).
constraint(c1,"int_lin_le").
in_constraint(c1,0,"X_103").
in_constraint(c1,1,array_at(0,"X_0")).
in_constraint(c1,1,array_at(1,"X_1")).
in_constraint(c1,2,-88).
solve(satisfy).
```

Similar for sets!

**Comment by MaxOstrowski** [comment]
As overloads are forbidden in minizinc, it should be clear from context (name of the constraint type) for me what's in the array, so maybe we can leave away the type information.

For parameters in constraints I would like to have something more distinguishable.
`in_constraint(C,I,X)` matches `X="X_103"` and `X=array_at(0,"X_0")`
So what about:
```
parameter("X_103",array,(0,1)).
parameter("X_103",array,(1,-1)).
...
in_constraint(c1,0,param,"X_103")
in_constraint(c1,1,array,(0,"X_0")).
in_constraint(c1,1,array,(1,"X_1")).
in_constraint(c1,1,set,"X_0").
in_constraint(c1,1,set,"X_1").
```

Multidimensional arrays could be implemented by simply extending the tuple,
so `x[1][2][3]=5` would be `parameter("x",array,(1,2,3,5))`.
What do you think...

**Comment by sthiele** [comment]
I like it like we do with variables.
Your example would look like this:
```
parameter("X_103",array,(0,1)).
parameter("X_103",array,(1,-1)).
...
constraint_type_at(c1,0,param)
constraint_value_at(c1,0,"X_103")
constraint_type_at(c1,1,array)
constraint_value_at(c1,1,(0,"X_0")).
constraint_value_at(c1,1,(1,"X_1")).
constraint_value(c1,1,(1,"X_1")).
constraint_type_at(c1,1,set).
constraint_value_at(c1,1,"X_0").
constraint_type_at(c1,1,set)
constraint_value_at(c1,1,set,"X_1")
```

Besides `set` and `array` ( of something) I could infer the types for concrete values like `bool`, `int`, `float` so `param` could be more fine grained. Otherwise I would call it `basic`.

**Comment by MaxOstrowski** [comment]
`constraint_type_at(c1,1,set).`
is printed twice in your example.
Otherwise I do not think that we need the type information there.
For flatzinc builtins, this is defined in the flatzinc manual.
For userdefined predicates you give this information using the `predicate` stuff.
So to keep the output simple and concise, I would drop the type in the `constraint_` information.

I do like the `constraint_type_at`, this is nice.

**Comment by sthiele** [comment]
I am printing type and values separated like that
```
array [1..2] of int: a = [1,-1];
```
translates to 
```
parameter_type("a",array(2,int)).
parameter_value("a",array,(0,1)).
parameter_value("a",array,(1,-1)).
```
and
```
set of int                            : si2 = 1..3;
```
translates to
```
parameter_type("si1",set_of_int).
parameter_value("si1",value,1).
parameter_type("si2",set_of_int).
parameter_value("si2",int_range,(1,3)).
```
if I have arrays of set like
```
array [1..3] of var set of {1,2,3}    : vas4 = [{1,2},1..3,{}]
```
i produce now this
```
variable_type("vas4",array(3,subset_of_int_set(1))).
variable_type("vas4",array(3,subset_of_int_set(2))).
variable_type("vas4",array(3,subset_of_int_set(3))).
variable_value("vas4",array,(0,value,1)).
variable_value("vas4",array,(0,value,2)).
variable_value("vas4",array,(1,int_range,(1,3))).
```
Can you spot the empty set?
Is this OK for you?

**Comment by MaxOstrowski** [comment]
> `parameter_type("a",array(2,int)).`

Nowhere else do we give the type of the array, why should we here.
`parameter_type("a", array)`
should be enough? and is consistent with the stuff in the constraints.
The size of the array is also given implicitly via the number of elements.

`parameter_value("a",array,(0,1)).`
Why should we double "array" here again. This is the value description, not the type, so maybe
`parameter_value("a",(0,1)).`
is enough ? and again consistent ?

```
parameter_type("si1",set_of_int).
parameter_value("si1",value,1).
```
I suppose that this comes from something like:
`set of int                            : si1 = {1};` ?

Doing the same thing with the array of sets could maybe look like:
```
variable_type("vas4",array).
variable_value("vas4",(0,value,1)).
variable_value("vas4",(0,value,2)).
variable_value("vas4",(1,int_range,(1,3))).
```
But now I'm screwed with the empty set :laughing: 
So what about
`variable_value("vas4",(2,int_range,(1,0))).`
But thats cheaty.

**Comment by MaxOstrowski** [comment]
As we do not need the type information for flatzingo, here is the information that we need with a format proposal:
Parameters of any kind:
```
parameter_value("a",int,1).         // single integer
parameter_value("b",float,"1.0").  // single float
parameter_value("c",bool,true).  // single bool
parameter_value("d",array,(0,42)). // array of int
parameter_value("d",array,(1,23)).
parameter_value("e",array,(0,"42.0")). // array of float
parameter_value("e",array,(1,"23.0")).
parameter_value("f",set,value,17)).     // set of int
parameter_value("f",set,range,(23,42))).
parameter_value("g",set,value,"23.0")).     // set of float
parameter_value("g",set,value,"42.0")).
parameter_value("h",array,(0,value,42)).  // array of set of int
parameter_value("h",array,(0,value,17)).
parameter_value("h",array,(1,range,(1,5))).
parameter_value("h",array,(1,value,42)).
parameter_value("h",array,(2,emptyset)).
```
Variable **assignments** of any kind.
I'm a bit confused about variables, as your variable example contains only fixed values and does not differ from a parameter. If they can contain other variables, 17 could also be replaced with "X" to reference another variable instead of an integer.
```
variable_value("a",int,1).         // single integer
variable_value("b",float,"1.0").  // single float
variable_value("c",bool,true).  // single bool
variable_value("c2",var,"X").  // single variable     c2=X
variable_value("d",array,(0,42)). // array of int
variable_value("d",array,(1,23)).
variable_value("d",array,(2,var,"X")).
variable_value("e",array,(0,"42.0")). // array of float
variable_value("e",array,(1,"23.0")).
variable_value("f",set,value,17)).     // set of var int
variable_value("f",set,var,"X")). 
variable_value("f",set,range,(23,42))).
variable_value("g",set,value,"23.0")).     // set of float
variable_value("g",set,value,"42.0")).
variable_value("h",array,(0,value,42)).  // array of set of var int
variable_value("h",array,(0,value,17)).
variable_value("h",array,(0,var,"X")).
variable_value("h",array,(1,range,(1,5))).
variable_value("h",array,(1,value,42)).
variable_value("h",array,(2,emptyset)).
```
Variables:
variable_type("a", int).
variable_type("b", float).
variable_type("c", bool).
variable_type("d", int_in_range,(23,42)).
variable_type("e", int_in_set,value,23).
variable_type("f", int_in_set,value,24).
variable_type("g", int_in_set,range,(42,72)).
variable_type("h",array(20,int_in_range,(17,23)))   // 20 elements of int in the range 17..23
.....

Constraints:
```
constraint(c1,"constraint_name").
// in_constraint(ID, parameter position, value)
rename constraint_value_at
in_constraint(c1,0,42).      // parameter 0 is integer 42
in_constraint(c1,1,"42.0").      // parameter 1 is float 42.0
in_constraint(c1,2,true).      // parameter 2 is bool true
in_constraint(c1,3,param,"a").      // parameter 4 is parameter "a", as defined by parameter_value("a",...
in_constraint(c1,4,var,"a").      // parameter 4 is variable "a", what ever this is
in_constraint(c1,5,array,(0,42)).      // parameter 5 is an array of integers and integer variables
in_constraint(c1,5,array,(1,17)).
in_constraint(c1,5,array,(2,"X")).   // sven weiss nicht ob X variable ist oder param
in_constraint(c1,5,array,(3,"X")).
in_constraint(c1,0,42).      // parameter 5 is integer 42
```

**Comment by MaxOstrowski** [comment]
@sven: Do I always get an extra `variable_type` for all variable assignemnts ?
If not, we have to change `variable_value` to `parameter_value`. Otherwise I can not distinguish parameters from variables in the encoding.

**Comment by MaxOstrowski** [comment]
I have some issues with array of integer variables.
Given the array `g`, consisting of 20 restricted integer variables.
`variable_type("g", array(20,int, set,(range,(17,23)))).   // 20 elements of int in the range 17..23`
and a constraint, that expected a single array of integer variables as input:
```
constraint(c1,"all_diff").
constraint_value(c1,0,var,"g").
```
I would need to fill this array with all 20 elements of `g`.
This works, as I have the knowledge that the constraint "all_diff" expects an array of variables, so I can defer that `g` is either an array of integer variables or a parameter of ints.
Now, how are the variables inside `g` named?
Would flatzinc/your converter produce something like:
```
constraint(c2,"non_zero"); // a constraint that constrains a single integer variable to be non zero
constraint_value(c2,0,"g[0]").
```
Or how are indiced variables named in your converter. A more lp'ish syntax would help, like
`constraint_value(c2,0,array_elem("g",0)).`

**Comment by sthiele** [comment]
Some clarifications:
- variable/parameter identifiers may only be declared once -> identifiers for parameters and variables are exclusive.

- The following statement is not allowed in flatzinc.
   ```
   var set of 17..42: e = {17,23..42}
   ```

   Expression like `1..3` are a short cut for `{1,2,3}`

**Comment by sthiele** [comment]
BTW: This Issue is going out of control. How about you create a branch adding a document describing your ideas for the translation the open a PR where we can discuss non linear.

**Comment by sthiele** [comment]
I opened a PR with the format proposal #15
