### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by MaxOstrowski** [sthiele/fzn2lp#12]
Flatzinc File generated from minizinc benchmark suite competition 2019.
Produces parse error.
[rotating.zip](https://github.com/sthiele/fzn2lp/files/4785996/rotating.zip)

**Comment by sthiele** [comment]
Looks like minizinc can't handle it's own output:
```
❯  cp rotating.fzn rotating.mzn
❯  minizinc -c --solver org.minizinc.mzn-fzn --output-fzn-to-stdout rotating.mzn
/home/.../rotating.mzn:1521.12-42:
MiniZinc: type error: no function or predicate with this signature found: `regular(array[int] of var int,int,int,array[int] of int,int,set of int)'
```
My parser stumble over ```array [int,int] ``` which is not in the flatzinc specs.

Maybe this is a bug in minizinc?

**Comment by MaxOstrowski** [comment]
Not a big. Occurs in many benchmarks with the global constraints. Just a 2D array. Don't know where the error lies... Google groups?

**Comment by sthiele** [comment]
Here is what the docs say

> Multidimensional arrays are supported by MiniZinc, but only single dimension arrays are supported by FlatZinc (at present). This means that multidimensional arrays must be mapped to single dimension arrays, and multidimensional array access must be mapped to single dimension array access.

So either the mapping is buggy or the docs are.

**Comment by MaxOstrowski** [comment]
This occurs when the redefinitions of chuffed are used.
Some of the global constraints in minizinc have 2d arrays as inputs.
`chuffed` simply translates these directly into flatzinc leaving the 2d array without any change.
I will ask in the google group about it as `chuffed` is a supported default solver and also `minizinc` produces these 2d arrays as output.
The `std` redefinitions translates all global constraints away, so it does not occur there.
But I found:
`array [1..100] of var int: heart:: output_array([1..10,1..10]) = [X_INTRODUCED_0_,0,0,0,0,0,0,0,0,0,X_INTRODUCED_10_,X_INTRODUCED_11_,0,0,0,0,0,0,0,0,X_INTRODUCED_20_,X_INTRODUCED_21_,X_INTRODUCED_22_,0,0,0,0,0,0,0,X_INTRODUCED_30_,X_INTRODUCED_31_,X_INTRODUCED_32_,X_INTRODUCED_33_,0,0,0,0,0,0,X_INTRODUCED_40_,X_INTRODUCED_41_,X_INTRODUCED_42_,X_INTRODUCED_43_,X_INTRODUCED_44_,0,0,0,0,0,X_INTRODUCED_50_,X_INTRODUCED_51_,X_INTRODUCED_52_,X_INTRODUCED_53_,X_INTRODUCED_54_,X_INTRODUCED_55_,0,0,0,0,X_INTRODUCED_60_,X_INTRODUCED_61_,X_INTRODUCED_62_,X_INTRODUCED_63_,X_INTRODUCED_64_,X_INTRODUCED_65_,X_INTRODUCED_66_,0,0,0,X_INTRODUCED_70_,X_INTRODUCED_71_,X_INTRODUCED_72_,X_INTRODUCED_73_,X_INTRODUCED_74_,X_INTRODUCED_75_,X_INTRODUCED_76_,X_INTRODUCED_77_,0,0,X_INTRODUCED_80_,X_INTRODUCED_81_,X_INTRODUCED_82_,X_INTRODUCED_83_,X_INTRODUCED_84_,X_INTRODUCED_85_,X_INTRODUCED_86_,X_INTRODUCED_87_,X_INTRODUCED_88_,0,X_INTRODUCED_90_,X_INTRODUCED_91_,X_INTRODUCED_92_,X_INTRODUCED_93_,X_INTRODUCED_94_,X_INTRODUCED_95_,X_INTRODUCED_96_,X_INTRODUCED_97_,X_INTRODUCED_98_,X_INTRODUCED_99_];`
in the `std` translation of the triangular benchmark.
Is this supported syntax ? Could you please check ? There is at least a 2d output array index in this line.

**Comment by MaxOstrowski** [comment]
https://groups.google.com/forum/#!topic/minizinc/bjzSUvETC5I

**Comment by MaxOstrowski** [comment]
It is confirmed that this is a bug in chuffed.
Could you still check the output_array thing ?
Afterwards, this can be closed.

**Comment by sthiele** [comment]
This works in the the meow branch
