### ISSUE TITLE
Output annotations

### ISSUE THREAD

**Issue by MaxOstrowski** [sthiele/fzn2lp#13]
We need them for the correct output for the minizinc competition:

https://www.minizinc.org/doc-2.4.3/en/fzn-spec.html#solution-output

Maybe you can find some examples of multi-dim output array flattening.
Otherwise, this is the only annotation that we currently need.

**Comment by sthiele** [comment]
related https://github.com/sthiele/flatzinc/issues/7

**Comment by sthiele** [comment]
How would you like the output?
For
```
var int : a :: output_var;
```
I would simply print
```
output_var("a").
```

For 
```
array [1..4] of var int : e :: output_array([1..2, 1..2]);
```
```
output_array("e",0,(1,2)).
output_array("e",1,(1,2)).

```

**Comment by MaxOstrowski** [comment]
Sounds awesome.
Are there any other more complicated output annotations?

**Comment by sthiele** [comment]
For output annotation that's it. But there are more annotations to guide the search.
