### ISSUE TITLE
weird array index

### ISSUE THREAD

**Issue by MaxOstrowski** [sthiele/fzn2lp#2]
Using the example

> minizinc-benchmarks/queens/queens.mzn minizinc-benchmarks/queens/004.dzn

results in this output
```
constraint(c0,"int_lin_ne").
in_constraint(c0,"int_lin_ne",0,"X_INTRODUCED_4_").
in_constraint(c0,1,array).
in_constraint(c0,1,0,"X_INTRODUCED_0_").
in_constraint(c0,1,1,"X_INTRODUCED_1_").
in_constraint(c0,"int_lin_ne",2,"0").
```
where instead of parameter 0 it is written `"int_lin_ne"`.
This is probably wrong, as I would have expected an array with coefficients (similar to parameter 1 but with integers).
Also the second parameter seems to have this
`in_constraint(c0,"int_lin_ne",2,"0").`
where `int_lin_ne` needs to be removed and `"0" `should probably be `0`.

**Comment by MaxOstrowski** [comment]
I had a more detailed look in the translation, and it seems that flatzinc produces some intermediate array for the constants [1,-1] that is reused in all constraints.
One way to handle it would be to flatten the output and replace occurences of this array with its actual content. I don't know if this should be a general thing...

**Comment by sthiele** [comment]
I removed the constraint identifier from the predicate now you get
```
constraint(c0,"int_lin_ne").
in_constraint(c0,0,"X_INTRODUCED_4_").
in_constraint(c0,1,array).
in_constraint(c0,1,0,"X_INTRODUCED_0_").
in_constraint(c0,1,1,"X_INTRODUCED_1_").
in_constraint(c0,2,"0").
```

**Comment by MaxOstrowski** [comment]
The last constant in this example should be `0` not `"0"`.

**Comment by MaxOstrowski** [comment]
You updated only branch "linewise". Is this the branch we use for development ?

**Comment by sthiele** [comment]
> The last constant in this example should be 0 not "0".
It is parsed as a float.
The quoting of floats might not be such a good idea because we don't know which type each parameter has.

**Comment by sthiele** [comment]
I work in linewise. It depends on what you want to change whether you open another branch.
