### ISSUE TITLE
2d arrays

### ISSUE THREAD

**Issue by MaxOstrowski** [sthiele/fzn2lp#3]
Going through
https://www.minizinc.org/doc-2.4.1/en/flattening.html
and wondering about some examples:

How could 
`constraint int_lin_eq([2, 1, -1, -2], [w[1], w[2], w[4], w[5]], 0);`
be translated.
Currently the complete example from the specification is
```
array[1..5] of var 0..3: w;
var -2..2: p
var 1..5: INT01;
constraint int_lin_eq([2, 1, -1, -2], [w[1], w[2], w[4], w[5]], 0);
constraint int_lin_eq([1, 1, 1, 1, 1], [w[1],w[2],w[3],w[4],w[5]], 5);
constraint array_var_int_element(INT01, w, 2);
constraint int_lin_eq([-1, 1], [INT01, p], -3);
```
which simply gives a syntax error that I do not understand.

**Comment by sthiele** [comment]
related issue #12

**Comment by MaxOstrowski** [comment]
Bug in chuffed:
https://groups.google.com/forum/#!topic/minizinc/bjzSUvETC5I

**Comment by sthiele** [comment]
Closing this. Multi dimensional arrays are currently not in the flatzinc specs, and the solution was to rather fix chuffeds translation.
