### ISSUE TITLE
Parser Error on self defined predicates

### ISSUE THREAD

**Issue by MaxOstrowski** [sthiele/fzn2lp#7]
Given the example.fzn
```
predicate int_eq_imp(var int: a,var int: b,var bool: r);
predicate int_le_imp(var int: a,var int: b,var bool: r);
predicate int_lin_le_imp(array [int] of int: c,array [int] of var int: x,int: d,var bool: b);
predicate flatzingo_fixed_disjunctive(array [int] of var opt int: s,array [int] of int: d);
predicate all_different_int(array [int] of var int: x);
predicate int_lin_eq_imp(array [int] of int: c,array [int] of var int: x,int: d,var bool: b);
predicate int_lin_ne_imp(array [int] of int: c,array [int] of var int: x,int: d,var bool: b);
array [1..2] of int: X_INTRODUCED_8160_ = [1,1];
array [1..3] of int: X_INTRODUCED_8162_ = [1,1,-1];
array [1..2] of int: X_INTRODUCED_8627_ = [-1,1];
```
`fzn2lp` reports
```
ERROR - ParseError: 0: at line 1, in Tag:
predicate flatzingo_fixed_disjunctive(array [int] of var opt int: s,array [int] of int: d);
^

1: at line 1, in Alt:
predicate flatzingo_fixed_disjunctive(array [int] of var opt int: s,array [int] of int: d);
^
```
Maybe this should go to https://github.com/sthiele/flatzinc ?

**Comment by MaxOstrowski** [comment]
Somehow that the elements in the array are optional (whatever this means).
Some constraints do have this. In my case I could remove it. But unsure if it is possible in theory and what it means ...

**Comment by sthiele** [comment]
https://www.minizinc.org/doc-2.4.3/en/lib-optiontypes.html

**Comment by sthiele** [comment]
If I run your example again through minizinc I get this.
```text
❯ minizinc -c --solver org.minizinc.mzn-fzn --output-fzn-to-stdout test.mzn
solve  satisfy;
```
Could it be that this unflattened minizinc?

**Comment by MaxOstrowski** [comment]
This should already be flatzinc.
Is is just a part of the file, like the first 10 lines, but should be valid flatzinc.

**Comment by MaxOstrowski** [comment]
Maybe this is an error with the opt thing that is not yet fully supported...
I removed the opt from my translation files and the error does not occur anymore.

**Comment by sthiele** [comment]
What's the next step? File a bug report at minizinc?

**Comment by MaxOstrowski** [comment]
Actually I do not know if it is bug.
Either we ignore it, as it resulted from an errornous translation file given by me,
or we post it in the minizinc mailing list. (It seems to be more active than the github issues)
I vote for ignore.
PS: the set thingy is only thing missing to be able to solve mzn problems now. Great!
